
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  password:
  user:

development:
  <<: *default
  database: mainoralho_api_development

test:
  <<: *default
  database: mainoralho_api_test

production:
  <<: *default
  database: mainoralho_api_production
  username: mainoralho_api
  password: <%= ENV["MAINORALHO_API_DATABASE_PASSWORD"] %>
